[package]
name = "rust-mongodb-adapter"
version = "0.1.0"
authors = ["george stoica <george_stoica@outlook.com>"]
edition = "2018"

[dependencies]
bson = "0.11.1"
mongo_driver = "0.12.1"
chrono = "0.4.6"